# This workflow is for a nightly run against WildFly upstream

name: WildFly Test Build

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

jobs:
  legacy-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['11', '17']
        wildfly-version: ['26.1.2.Final']

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }}
        run: mvn -B clean verify '-Dorg.wildfly.logging.skipLogManagerCheck=true' '-Dversion.org.wildfly.full=${{ matrix.wildfly-version }}' '-Dwildfly.preview'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'

  wildfly-build:
    runs-on: ubuntu-latest
    outputs:
      wildfly-version: ${{steps.version.outputs.wildfly-version}}
    steps:
      - name: Checkout WildFly
        uses: actions/checkout@v3
        with:
          repository: wildfly/wildfly
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Build WildFly
        run: 'mvn clean install -DskipTests -Dcheckstyle.skip=true -Denforcer.skip=true'
      - id: version
        run: echo "::set-output name=wildfly-version::$(mvn -B help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
      - name: Archive the repository
        run: tar -czf maven-repository.tgz -C ~ .m2/repository
      - uses: actions/upload-artifact@v3
        with:
          name: maven-repository
          path: maven-repository.tgz
          retention-days: 5

  wildfly-arquillin-build:
    runs-on: ${{ matrix.os }}
    needs: wildfly-build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: ['11', '17']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzf maven-repository.tgz -C ~
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }}
        run: mvn clean verify '-Dorg.wildfly.logging.skipLogManagerCheck=true' '-Dversion.org.wildfly.full=${{needs.wildfly-build.outputs.wildfly-version}}' '-Dversion.org.wildfly=${{needs.wildfly-build.outputs.wildfly-version}}'
      - name: Upload surefire reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      - name: Upload server logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'
      - name: Delete the shared repository
        uses: geekyeggo/delete-artifact@v2
        with:
          name: maven-repository
          failOnError: false
